# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyhttp" do
  version "0.21.0"

  on_macos do
    on_intel do
      sha256 "db52513d2fc05ccadfe12575aed672ae8f541586f83f53134f969c81a015dc66"
      url "https://github.com/wingedsheep/lazyhttp/releases/download/v#{version}/lazyhttp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "80da043b63fe8f25c3634d9b168f5fa8f81259de94fa711dabe0c927209f71ad"
      url "https://github.com/wingedsheep/lazyhttp/releases/download/v#{version}/lazyhttp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fee3a269deef7b6a74adeed91e314076e782c287838a065b004b53cff939210e"
      url "https://github.com/wingedsheep/lazyhttp/releases/download/v#{version}/lazyhttp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a33ffbd472bf2652e9171676264a6346a603ebaf749993b6dabcb7736f4c6dc6"
      url "https://github.com/wingedsheep/lazyhttp/releases/download/v#{version}/lazyhttp_linux_arm64.tar.gz"
    end
  end

  name "lazyhttp"
  desc "Terminal UI for running .http test plans step by step"
  homepage "https://github.com/wingedsheep/lazyhttp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyhttp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyhttp"]
    end
  end

  # No zap stanza required

end
