# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyhttp" do
  version "0.18.2"

  on_macos do
    on_intel do
      sha256 "318126fa21475dee53eafcd6911617f350ffef1b2ac2bc6c252b596714f0ca51"
      url "https://github.com/wingedsheep/lazyhttp/releases/download/v#{version}/lazyhttp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b9fe4467d5186ac651ce08caeac9781f45c1b908330b79ca1b121f46e4dfb0b"
      url "https://github.com/wingedsheep/lazyhttp/releases/download/v#{version}/lazyhttp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "339c5c494b4c8fbd29846d0149bad5697f91e3f0c8e92a578e4505b42a2b7738"
      url "https://github.com/wingedsheep/lazyhttp/releases/download/v#{version}/lazyhttp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0edeca34b4821f6d42ff0faefe62c75a26f7e54a271fb9cc33de46df6212396f"
      url "https://github.com/wingedsheep/lazyhttp/releases/download/v#{version}/lazyhttp_linux_arm64.tar.gz"
    end
  end

  name "lazyhttp"
  desc "Terminal UI for running .http test plans step by step"
  homepage "https://github.com/wingedsheep/lazyhttp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyhttp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyhttp"]
    end
  end

  # No zap stanza required

end
