# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyhttp" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "4fbd07ccb7a45ec02872126d2afd4dc419e73c1e749f672cd9c5a20f19b3f177"
      url "https://github.com/wingedsheep/lazyhttp/releases/download/v#{version}/lazyhttp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3c9cef18a0b2b3a1fa33433b0bbc0a64a01a0475c99d1b4e684ac330ddea74d"
      url "https://github.com/wingedsheep/lazyhttp/releases/download/v#{version}/lazyhttp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1e8f97c8b9f542c552c3997b143ff5c5533801279899358f039ef31779db8507"
      url "https://github.com/wingedsheep/lazyhttp/releases/download/v#{version}/lazyhttp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "00c4eaa12cfcb0e322baf47fcf738dd3b8b24cc773da90417548b7dade5fb3d2"
      url "https://github.com/wingedsheep/lazyhttp/releases/download/v#{version}/lazyhttp_linux_arm64.tar.gz"
    end
  end

  name "lazyhttp"
  desc "Terminal UI for running .http test plans step by step"
  homepage "https://github.com/wingedsheep/lazyhttp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyhttp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyhttp"]
    end
  end

  # No zap stanza required

end
